{
  "openapi": "3.0.0",
  "info": {
    "title": "Fuse Mock API",
    "version": "1.0.0",
    "contact": {
      "url": "http://fusetheme.com/",
      "email": "themes@withinpixels.com",
      "name": "Fuse Theme"
    },
    "description": "Fuse Theme Family Mock API Open API Definitions",
    "license": {
      "name": "private",
      "url": "https://themeforest.net/licenses/terms/regular"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "database": {
    "channels": {
      "value": [
        {
          "id": 1,
          "user_id": "aaa",
          "media": "aaa",
          "channel": "aaa",
          "created_at": "2023-12-26T13:58:04.000000Z",
          "updated_at": "2023-12-26T13:58:04.000000Z"
        },
        {
          "id": 2,
          "user_id": "qwe",
          "media": "qwe",
          "channel": "qwe",
          "created_at": "2023-12-26T13:58:04.000000Z",
          "updated_at": "2023-12-26T13:58:04.000000Z"
        },
        {
          "id": 3,
          "user_id": "asd",
          "media": "asd",
          "channel": "asd",
          "created_at": "2023-12-26T13:58:04.000000Z",
          "updated_at": "2023-12-26T13:58:04.000000Z"
        },
        {
          "id": 4,
          "user_id": "rty",
          "media": "rty",
          "channel": "rty",
          "created_at": "2023-12-26T13:58:04.000000Z",
          "updated_at": "2023-12-26T13:58:04.000000Z"
        }
      ]
    },
    "offers": {
      "value": [
        {
          "id": 1,
          "id_idcgame": "1304",
          "offer_id": 0,
          "game_name": "1812: Napoleon Wars",
          "game_seo": "1812-napoleon-wars",
          "percent": 15
        },
        {
          "id": 2,
          "id_idcgame": "1219",
          "offer_id": 0,
          "game_name": "999",
          "game_seo": "999",
          "percent": 15
        },
        {
          "id": 3,
          "id_idcgame": "1298",
          "offer_id": 0,
          "game_name": "A Story of Distress",
          "game_seo": "a-story-of-distress",
          "percent": 15
        },
        {
          "id": 4,
          "id_idcgame": "1091",
          "offer_id": 0,
          "game_name": "Abandon Ship",
          "game_seo": "abandon-ship",
          "percent": 15
        },
        {
          "id": 5,
          "id_idcgame": "1242",
          "offer_id": 0,
          "game_name": "Adam Wolfe",
          "game_seo": "adam-wolfe",
          "percent": 15
        },
        {
          "id": 6,
          "id_idcgame": "1183",
          "offer_id": 0,
          "game_name": "Admiral Nemo",
          "game_seo": "admiral-nemo",
          "percent": 15
        },
        {
          "id": 7,
          "id_idcgame": "1176",
          "offer_id": 0,
          "game_name": "Adventures of Chris",
          "game_seo": "adventures-of-chris",
          "percent": 15
        },
        {
          "id": 8,
          "id_idcgame": "1127",
          "offer_id": 0,
          "game_name": "Aery - A Journey Beyond Time",
          "game_seo": "aery-a-journey-beyond-time",
          "percent": 15
        },
        {
          "id": 9,
          "id_idcgame": "1169",
          "offer_id": 0,
          "game_name": "Aery - Calm Mind",
          "game_seo": "aery-calm-mind",
          "percent": 15
        },
        {
          "id": 10,
          "id_idcgame": "1109",
          "offer_id": 0,
          "game_name": "Aery - Sky Castle",
          "game_seo": "aery-sky-castle",
          "percent": 15
        },
        {
          "id": 11,
          "id_idcgame": "1128",
          "offer_id": 0,
          "game_name": "Aery \u2013 Broken Memories",
          "game_seo": "aery-broken-memories",
          "percent": 15
        },
        {
          "id": 12,
          "id_idcgame": "1129",
          "offer_id": 0,
          "game_name": "Aery \u2013 Little Bird Adventure",
          "game_seo": "aery-little-bird-adventure",
          "percent": 15
        },
        {
          "id": 13,
          "id_idcgame": "1130",
          "offer_id": 0,
          "game_name": "Air Bounce - The Jump n Run Challenge",
          "game_seo": "air-bounce-the-jump-n-run-challenge",
          "percent": 15
        },
        {
          "id": 14,
          "id_idcgame": "1334",
          "offer_id": 0,
          "game_name": "Airport Madness 3D: Volume 1",
          "game_seo": "airport-madness-3d-volume-1",
          "percent": 15
        },
        {
          "id": 15,
          "id_idcgame": "1328",
          "offer_id": 0,
          "game_name": "Airport Madness 3D: Volume 2",
          "game_seo": "airport-madness-3d-volume-2",
          "percent": 15
        },
        {
          "id": 16,
          "id_idcgame": "1397",
          "offer_id": 0,
          "game_name": "All My Gods",
          "game_seo": "all-my-gods",
          "percent": 15
        },
        {
          "id": 17,
          "id_idcgame": "1220",
          "offer_id": 0,
          "game_name": "Alter Army",
          "game_seo": "alter-army",
          "percent": 15
        },
        {
          "id": 18,
          "id_idcgame": "1218",
          "offer_id": 0,
          "game_name": "Alterity Experience",
          "game_seo": "alterity-experience",
          "percent": 15
        },
        {
          "id": 19,
          "id_idcgame": "1093",
          "offer_id": 0,
          "game_name": "An Interesting Journey of Monsieur PAF",
          "game_seo": "an-interesting-journey-of-monsieur-paf",
          "percent": 15
        },
        {
          "id": 20,
          "id_idcgame": "1251",
          "offer_id": 0,
          "game_name": "Anatomy of Fear",
          "game_seo": "anatomy-of-fear",
          "percent": 15
        },
        {
          "id": 21,
          "id_idcgame": "1184",
          "offer_id": 0,
          "game_name": "Antifector",
          "game_seo": "antifector",
          "percent": 15
        },
        {
          "id": 22,
          "id_idcgame": "1186",
          "offer_id": 0,
          "game_name": "Arizona Derby: Offroad Wars",
          "game_seo": "arizona-derby-offroad-wars",
          "percent": 15
        },
        {
          "id": 23,
          "id_idcgame": "1237",
          "offer_id": 0,
          "game_name": "Asteroid Hideout",
          "game_seo": "asteroid-hideout",
          "percent": 15
        },
        {
          "id": 24,
          "id_idcgame": "1255",
          "offer_id": 0,
          "game_name": "Athopiu - The Final Rebirth of Hopeless Incarnate",
          "game_seo": "athopiu-the-final-rebirth-of-hopeless-incarnate",
          "percent": 15
        },
        {
          "id": 25,
          "id_idcgame": "1412",
          "offer_id": 0,
          "game_name": "Attempt[42]",
          "game_seo": "attempt42",
          "percent": 15
        },
        {
          "id": 26,
          "id_idcgame": "1332",
          "offer_id": 0,
          "game_name": "Avirion Chronicles \u2013 Genealogy of the Great Crusaders",
          "game_seo": "avirion-chronicles-\u2013-genealogy-of-the-great-crusaders",
          "percent": 15
        },
        {
          "id": 27,
          "id_idcgame": "1070",
          "offer_id": 0,
          "game_name": "Back To Bed",
          "game_seo": "back-to-bed",
          "percent": 15
        },
        {
          "id": 28,
          "id_idcgame": "1027",
          "offer_id": 0,
          "game_name": "Bad North",
          "game_seo": "bad-north",
          "percent": 15
        },
        {
          "id": 29,
          "id_idcgame": "1185",
          "offer_id": 0,
          "game_name": "Badminton Warrior",
          "game_seo": "badminton-warrior",
          "percent": 15
        },
        {
          "id": 30,
          "id_idcgame": "1410",
          "offer_id": 0,
          "game_name": "BalanCity",
          "game_seo": "balancity",
          "percent": 15
        }
      ]
    },
    "links": {
      "value": [
        {
          "id": 59,
          "offer_id": 0,
          "game_id": 1219,
          "influencer_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
          "id_idcgame": 1219,
          "revenue_idc": 15,
          "revenue_game": 20,
          "link_expire_at": "2024-12-27",
          "utm_source": "idcinfluencer",
          "utm_medium": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1_asdasdasdasd_123",
          "utm_campaign": "59_999",
          "created_at": "2023-12-27T15:28:34.000000Z",
          "updated_at": "2023-12-27T15:28:34.000000Z",
          "link_game_home": "https:\/\/en.idcgames.com\/999?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_asdasdasdasd_123&utm_campaign=59_999",
          "link_landing": "https:\/\/en.idcgames.com\/999\/landing?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_asdasdasdasd_123&utm_campaign=59_999",
          "game": {
            "id": 1219,
            "name": "999",
            "seo_name": "999",
            "folder_name": "999",
            "company": 83,
            "status": 7,
            "complete": true,
            "production": true,
            "for_community": false,
            "created_at": "2021-07-07T15:25:45.000000Z",
            "updated_at": "2021-07-15T07:13:36.000000Z",
            "deleted_at": null,
            "logo_media_id": 5820,
            "default_price": "7.99",
            "default_currency": "EUR"
          }
        },
        {
          "id": 58,
          "offer_id": 0,
          "game_id": 1219,
          "influencer_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
          "id_idcgame": 1219,
          "revenue_idc": 15,
          "revenue_game": 20,
          "link_expire_at": "2024-12-27",
          "utm_source": "idcinfluencer",
          "utm_medium": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe",
          "utm_campaign": "58_999",
          "created_at": "2023-12-27T15:28:03.000000Z",
          "updated_at": "2023-12-27T15:28:03.000000Z",
          "link_game_home": "https:\/\/en.idcgames.com\/999?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=58_999",
          "link_landing": "https:\/\/en.idcgames.com\/999\/landing?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=58_999",
          "game": {
            "id": 1219,
            "name": "999",
            "seo_name": "999",
            "folder_name": "999",
            "company": 83,
            "status": 7,
            "complete": true,
            "production": true,
            "for_community": false,
            "created_at": "2021-07-07T15:25:45.000000Z",
            "updated_at": "2021-07-15T07:13:36.000000Z",
            "deleted_at": null,
            "logo_media_id": 5820,
            "default_price": "7.99",
            "default_currency": "EUR"
          }
        },
        {
          "id": 57,
          "offer_id": 0,
          "game_id": 1219,
          "influencer_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
          "id_idcgame": 1219,
          "revenue_idc": 15,
          "revenue_game": 20,
          "link_expire_at": "2024-12-26",
          "utm_source": "idcinfluencer",
          "utm_medium": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe",
          "utm_campaign": "57_999",
          "created_at": "2023-12-26T16:11:12.000000Z",
          "updated_at": "2023-12-26T16:11:12.000000Z",
          "link_game_home": "https:\/\/en.idcgames.com\/999?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=57_999",
          "link_landing": "https:\/\/en.idcgames.com\/999\/landing?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=57_999",
          "game": {
            "id": 1219,
            "name": "999",
            "seo_name": "999",
            "folder_name": "999",
            "company": 83,
            "status": 7,
            "complete": true,
            "production": true,
            "for_community": false,
            "created_at": "2021-07-07T15:25:45.000000Z",
            "updated_at": "2021-07-15T07:13:36.000000Z",
            "deleted_at": null,
            "logo_media_id": 5820,
            "default_price": "7.99",
            "default_currency": "EUR"
          }
        },
        {
          "id": 56,
          "offer_id": 0,
          "game_id": 1219,
          "influencer_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
          "id_idcgame": 1219,
          "revenue_idc": 15,
          "revenue_game": 20,
          "link_expire_at": "2024-12-26",
          "utm_source": "idcinfluencer",
          "utm_medium": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe",
          "utm_campaign": "56_999",
          "created_at": "2023-12-26T16:11:06.000000Z",
          "updated_at": "2023-12-26T16:11:06.000000Z",
          "link_game_home": "https:\/\/en.idcgames.com\/999?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=56_999",
          "link_landing": "https:\/\/en.idcgames.com\/999\/landing?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=56_999",
          "game": {
            "id": 1219,
            "name": "999",
            "seo_name": "999",
            "folder_name": "999",
            "company": 83,
            "status": 7,
            "complete": true,
            "production": true,
            "for_community": false,
            "created_at": "2021-07-07T15:25:45.000000Z",
            "updated_at": "2021-07-15T07:13:36.000000Z",
            "deleted_at": null,
            "logo_media_id": 5820,
            "default_price": "7.99",
            "default_currency": "EUR"
          }
        },
        {
          "id": 55,
          "offer_id": 0,
          "game_id": 1091,
          "influencer_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
          "id_idcgame": 1091,
          "revenue_idc": 15,
          "revenue_game": 20,
          "link_expire_at": "2024-12-26",
          "utm_source": "idcinfluencer",
          "utm_medium": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe",
          "utm_campaign": "55_abandon-ship",
          "created_at": "2023-12-26T13:16:33.000000Z",
          "updated_at": "2023-12-26T13:16:33.000000Z",
          "link_game_home": "https:\/\/en.idcgames.com\/abandon-ship?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=55_abandon-ship",
          "link_landing": "https:\/\/en.idcgames.com\/abandon-ship\/landing?utm_source=idcinfluencer&utm_medium=XgbuVEXBU5gtSKdbQRP1Zbbby1i1_qwe_qwe&utm_campaign=55_abandon-ship",
          "game": {
            "id": 1091,
            "name": "Abandon Ship",
            "seo_name": "abandon-ship",
            "folder_name": "Abandon Ship",
            "company": 23,
            "status": 7,
            "complete": true,
            "production": true,
            "for_community": false,
            "created_at": "2020-09-24T07:46:55.000000Z",
            "updated_at": "2021-02-01T10:46:04.000000Z",
            "deleted_at": null,
            "logo_media_id": 389,
            "default_price": "22.99",
            "default_currency": "EUR"
          }
        }
      ]
    }
  },
  "components": {
    "examples": {
      "auth_users": {
        "value": [
          {
            "id": 1,
            "user_id": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
            "from": "custom-db",
            "password": "aaa",
            "role": "admin",
            "displayName": "Abbott Keitch",
            "firstname": "Abbott",
            "lastname": "Keitch",
            "photoURL": "assets/images/avatars/brian-hughes.jpg",
            "email": "admin@admin.com",
            "vat_number": "0148594",
            "address_line1": "100 Menahan Street",
            "address_line2": "Snyderville, Kansas, PO1006"
          },
          {
            "id": 2,
            "user_id": "XgbuVEXBU6gtSKdbTYR1Zbbby1i3",
            "from": "custom-db",
            "password": "staff",
            "role": "staff",
            "data": {
              "displayName": "Arnold Matlock",
              "photoURL": "assets/images/avatars/Arnold.jpg",
              "email": "staff@fusetheme.com",
              "settings": {
                "layout": {
                  "style": "layout2",
                  "config": {
                    "mode": "boxed",
                    "scroll": "content",
                    "navbar": {
                      "display": true
                    },
                    "toolbar": {
                      "display": true,
                      "position": "below"
                    },
                    "footer": {
                      "display": true,
                      "style": "fixed"
                    }
                  }
                },
                "customScrollbars": true,
                "theme": {}
              },
              "shortcuts": [
                "apps.calendar",
                "apps.mailbox",
                "apps.contacts",
                "apps.tasks"
              ]
            }
          }
        ]
      },
      "notifications": {
        "value": [
          {
            "id": "493190c9-5b61-4912-afe5-78c21f1044d7",
            "icon": "heroicons-solid:star",
            "title": "Daily challenges",
            "description": "Your submission has been accepted",
            "time": "2022-05-09T10:32:42.703Z",
            "read": false
          },
          {
            "id": "6e3e97e5-effc-4fb7-b730-52a151f0b641",
            "image": "assets/images/avatars/male-04.jpg",
            "description": "<strong>Leo Gill</strong> added you to <em>Top Secret Project</em> group and assigned you as a <em>Project Manager</em>",
            "time": "2022-05-09T10:07:42.703Z",
            "read": true,
            "link": "/dashboards/project",
            "useRouter": true
          },
          {
            "id": "b91ccb58-b06c-413b-b389-87010e03a120",
            "icon": "heroicons-solid:mail",
            "title": "Mailbox",
            "description": "You have 15 unread mails across 3 mailboxes",
            "time": "2022-05-09T07:57:42.703Z",
            "read": false,
            "link": "/apps/mailbox",
            "useRouter": true
          },
          {
            "id": "541416c9-84a7-408a-8d74-27a43c38d797",
            "icon": "heroicons-solid:refresh",
            "title": "Cron jobs",
            "description": "Your <em>Docker container</em> is ready to publish",
            "time": "2022-05-09T05:57:42.703Z",
            "read": false,
            "link": "/dashboards/project",
            "useRouter": true
          },
          {
            "id": "ef7b95a7-8e8b-4616-9619-130d9533add9",
            "image": "assets/images/avatars/male-06.jpg",
            "description": "<strong>Roger Murray</strong> accepted your friend request",
            "time": "2022-05-09T03:57:42.703Z",
            "read": true,
            "link": "/dashboards/project",
            "useRouter": true
          },
          {
            "id": "eb8aa470-635e-461d-88e1-23d9ea2a5665",
            "image": "assets/images/avatars/female-04.jpg",
            "description": "<strong>Sophie Stone</strong> sent you a direct message",
            "time": "2022-05-09T01:57:42.703Z",
            "read": true,
            "link": "/dashboards/project",
            "useRouter": true
          },
          {
            "id": "b85c2338-cc98-4140-bbf8-c226ce4e395e",
            "icon": "heroicons-solid:mail",
            "title": "Mailbox",
            "description": "You have 3 new mails",
            "time": "2022-05-08T10:57:42.703Z",
            "read": true,
            "link": "/apps/mailbox",
            "useRouter": true
          },
          {
            "id": "8f8e1bf9-4661-4939-9e43-390957b60f42",
            "icon": "heroicons-solid:star",
            "title": "Daily challenges",
            "description": "Your submission has been accepted and you are ready to sign-up for the final assigment which will be ready in 2 days",
            "time": "2022-05-06T10:57:42.703Z",
            "read": true,
            "link": "/dashboards/project",
            "useRouter": true
          },
          {
            "id": "30af917b-7a6a-45d1-822f-9e7ad7f8bf69",
            "icon": "heroicons-solid:refresh",
            "title": "Cron jobs",
            "description": "Your Vagrant container is ready to download",
            "time": "2022-05-05T10:57:42.703Z",
            "read": true,
            "link": "/apps/file-manager",
            "useRouter": true
          }
        ]
      }
    }
  }
}